/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104353-g2c734a8496-20211015"
#endif /* AVUTIL_FFVERSION_H */
